stages:
  - php
  - build
  # - bdd
  # - release

variables:
  DOCKER_HOST: tcp://docker:2375
  GIT_DEPTH: 10
  GIT_SUBMODULE_STRATEGY: recursive

build-php-linux:
  stage: php
  image: docker:20.10-git
  services:
    - docker:20.10-dind
  script:
    - apk add -U make
    - mkdir -p legacy/archives
    - make php
  artifacts:
    paths:
      - legacy/archives/*
    expire_in: 1 day

build-php-windows:
  stage: php
  image: docker:20.10-git
  script:
    - apk add -U make wget
    - mkdir -p legacy/archives
    - make php GOOS=windows GOARCH=amd64
  artifacts:
    paths:
      - legacy/archives/*
    expire_in: 1 day

build:
  stage: build
  image:
    name: goreleaser/goreleaser:v1.9.2
    entrypoint: [""]
  script: make single
  dependencies:
    - build-php-linux
    - build-php-windows
  artifacts:
    paths:
      - dist/platform_*
      - dist/checksums.txt
    expire_in: 1 day
