stages:
  - php
  - build
  # - bdd
  # - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 10

build-php-linux:
  stage: php
  image: homebrew/brew
  script:
    - mkdir -p legacy/archives
    - make php
  artifacts:
    paths:
      - legacy/archives/*
    expire_in: 1 day

build-php-windows:
  stage: php
  image: homebrew/brew
  script:
    - mkdir -p legacy/archives
    - make php GOOS=windows GOARCH=amd64
  artifacts:
    paths:
      - legacy/archives/*
    expire_in: 1 day

build:
  stage: build
  image:
    name: goreleaser/goreleaser:v1.9.2
    entrypoint: [""]
  script: make single
  dependencies:
    - build-php-linux
    - build-php-windows
  artifacts:
    paths:
      - dist/platform_*
      - dist/checksums.txt
    expire_in: 1 day
